=== CeiB0T/SWEP-Kochbuch/XMLundDTDs/Rezept.dtd
<!ELEMENT rezept (rkopf, rinhalt)>
<!ATTLIST rezept rid ID #REQUIRED>

<!ELEMENT rkopf (titel,anzahl?,zutat*)>
<!ATTLIST rkopf datum CDATA #REQUIRED>
<!ATTLIST rkopf aenderung CDATA #REQUIRED>

<!ELEMENT titel (#CDATA)>
<!ELEMENT anzahl (#CDATA)>
<!ELEMENT zutat (#CDATA)>
<!ATTLIST zutat zid IDREF #IMPLIED -- Gibt Freiwillig Referenz auf Zutat mit ID -->
<!ATTLIST zutat menge CDATA #IMPLIED>
<!ATTLIST zutat mengeneinheit CDATA #IMPLIED>

<!ELEMENT rinhalt (#CDATA,zmsubstring*)>
<!ELEMENT zmsubstring (#CDATA)>
<!ATTLIST zmsubstring zmid IDREF #REQUIERD>
<!ATTLIST zmsubstring zmbeginn CDATA #REQUIERD>
<!ATTLIST zmsubstring zmende CDATA #REQUIERD>

=== CeiB0T/SWEP-Kochbuch/XMLundDTDs/beispielrezept.xml
<?xml version="1.0"?>
<!DOCTYPE rezept SYSTEM "Rezept.dtd">

<rezept rid=1>
	<rkopf datum="2022-03-18" aenderung="2022-03-18">
		<title>Apfelringe</title>
		<anzahl>12</anzahl>
		<zutat zid=12></zutat> <!-- Ueber ID referenzierte Zutat -->
		<zutat menge="1" mengeneinheit="Prise">Zimt</zutat>
	</rkopf>
	<rinhalt>Ã„pfel waschen und in scheiben Schneiden
	<zmsubstring zmid=14 zmbeginn=41 zmende=49>trocknen</zmsubstring> und mit Zimt bestreuen</rinhalt>
</rezept>
